language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.4
    - otp_release: 20.0
      elixir: 1.5
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, test"
after_success:
  - "mix coveralls.travis"
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
